### ISSUE TITLE
Changes in dungeon sizes do not work

### ISSUE THREAD

**Issue by Hiranus** [JereKuusela/valheim-expand_world#24]
[expand_dungeons.txt](https://github.com/JereKuusela/valheim-expand_world/files/13328444/expand_dungeons.txt)
I changed file type because github won't allow me to upload yaml
I did these changes so that dungeons etc would be massive but it seems like its not working. I tried resetting dungeons with UpgradeWorld multiple times but nothing changed.

**Comment by JereKuusela** [comment]
Most dungeons don't have any verticality so the area is very limited.

You can increase bounds to make it expand on adjacent zones, but this requires everyone to have the mod.

Another idea is to try increase the chance of room forestcrypt_Chasm01, because that's the one tha enables multiple levels.

You can remove minPlaceOrder from it so that it can appear closer to the entrance and set it as the requiredRooms.

**Comment by JereKuusela** [comment]
Another idea is to add a custom type to a single connection of forestcrypt_Chasm01 and forestcrypt_entrance_large rooms to make it always appear after entrance.

Or even a custom blueprint room that adds verticality to the dungeon.
